# Tutorial 0: Introduction to PyTorch

*This is an empty version of the notebook. Try to fill in the blanks indicated by `## TODO` comments and `...` parts in the code*.

> This Jupyter notebook is intended solely for your practice and will not be subject to grading. We will discuss its contents during the tutorial on November 7th. Please use it as an opportunity to learn. 😊

Welcome to our PyTorch tutorial for the Neural Networks for NLP (NNNLP) course. This notebook is designed to provide a concise introduction to the fundamentals of PyTorch and prepare you for creating your own neural networks. PyTorch is an open-source machine learning framework that allows you to develop and optimize neural networks effectively. It's important to note that PyTorch is just one of several frameworks available for this purpose. Alternatives to PyTorch include [TensorFlow](https://www.tensorflow.org/), [JAX](https://github.com/google/jax#quickstart-colab-in-the-cloud), and [Caffe](http://caffe.berkeleyvision.org/).

Our choice to focus on PyTorch is rooted in its established reputation, a thriving developer community (originally developed by Facebook), flexibility, and widespread use in research. Many research papers release their code in PyTorch, making it essential to be well-versed in this framework. On the other hand, TensorFlow, developed by Google, is recognized for its role as a production-grade deep learning library. Fortunately, once you become proficient in one machine learning framework, transitioning to another becomes easier, as they share common concepts and ideas. For example, TensorFlow version 2 drew inspiration from the most popular features of PyTorch, further aligning the frameworks.

If you're already familiar with PyTorch and have experience with creating your own neural network projects, you can skim through this notebook.

We acknowledge that we are not the first to offer a PyTorch tutorial. Numerous excellent tutorials are available online, including the ["60-min blitz"](https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html) on the official [PyTorch website](https://pytorch.org/tutorials/) and the ["UvA Deep Learning Tutorials"](https://github.com/phlippe/uvadlc_notebooks/tree/master) (from which we drew inspiration). However, we've tailored our tutorial to provide the essential knowledge required for practical NLP applications while ensuring an understanding of PyTorch's inner workings. In the coming weeks, we will continue to explore new PyTorch features in our series of Jupyter notebook tutorials for NNNLP.

Throughout this tutorial, we will make use of standard libraries commonly employed in machine learning projects. If you are running this notebook on Google Colab, these libraries should already be pre-installed. However, if you are running this notebook locally, please create an environment and install these libraries as necessary. You can refer to the guide ["Getting started with conda"](https://conda.io/projects/conda/en/latest/user-guide/getting-started.html) for instructions on creating environments.

In [196]:
import os
import math
import numpy as np 
import time
import matplotlib.pyplot as plt
%matplotlib inline 
from IPython.display import set_matplotlib_formats
import matplotlib_inline.backend_inline
matplotlib_inline.backend_inline.set_matplotlib_formats('svg', 'pdf') 
from matplotlib.colors import to_rgba
import seaborn as sns
sns.set()
from tqdm.notebook import tqdm

## Exploring PyTorch Fundamentals

To begin, let's delve into the fundamental concepts of PyTorch. It's recommended that you have some familiarity with the `numpy` package, as most machine learning frameworks are built upon similar principles. If you're not already acquainted with `numpy`, don't worry. You can follow this [tutorial](https://numpy.org/devdocs/user/quickstart.html) to get up to speed.

Now, let's kick things off by importing PyTorch. The package is named `torch` and is derived from the original [Torch](http://torch.ch/) framework. As a starting point, let's check the version of PyTorch:

In [197]:
import torch
print("Using torch", torch.__version__)

Using torch 2.3.1+cu121


As of the time of creating this tutorial in October 2023, the current stable version of PyTorch is 2.1. When you execute the code, you should expect to see the output `Using torch 2.1`. If you encounter a lower version number, please ensure that you have set up the correct environment or reach out to us for assistance. Fortunately, the interface between different PyTorch versions remains relatively consistent, so the code should remain compatible with newer releases.

In the realm of machine learning frameworks, PyTorch, like others, offers functions that involve randomness, such as generating random numbers. However, it's a best practice to configure your code in a way that ensures it can produce the same results with the same random numbers every time it's run. This is why we set a seed in the code below.

In [198]:
torch.manual_seed(0) # Setting the seed (0 for tutorial 0 :p)

### Introduction to Tensors

Tensors serve as PyTorch's counterpart to Numpy arrays, and they come with the added advantage of GPU acceleration support, which we will explore further later on. The term "tensor" is a broad concept that encompasses structures you are already familiar with. For example, a vector corresponds to a 1-D tensor, while a matrix is represented as a 2-D tensor. Check this video on ["what's a Tensor"](https://www.youtube.com/watch?v=f5liqUk0ZTw). In the context of neural networks, we manipulate tensors of various shapes and dimensions.

You can perform most of the common operations that you are accustomed to in Numpy on tensors. In fact, because tensors and Numpy arrays are so alike, you can easily convert tensors to Numpy arrays and vice versa, although this is not frequently necessary.

### Tensor Initialization

Let's begin by examining the various methods available for creating tensors. There are numerous options to choose from, but the simplest one involves using the `torch.Tensor` constructor and providing the desired shape as an input argument.

In [201]:
x = torch.Tensor(3, 2, 3)
print(x)
print(x.shape) 

tensor([[[-4.1695e+01,  3.6229e-41, -2.6122e+05],
         [ 3.6229e-41,  1.1210e-43,  0.0000e+00]],

        [[ 8.9683e-44,  0.0000e+00,  7.9101e+09],
         [ 8.4078e-45,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  1.4013e-45,  0.0000e+00]]])
torch.Size([3, 2, 3])


The function `torch.Tensor` allocates memory for the desired tensor, but reuses any values that have already been in the memory. To directly assign values to the tensor during initialization, there are many alternatives including:

* `torch.zeros`: Creates a tensor filled with zeros
* `torch.ones`: Creates a tensor filled with ones
* `torch.rand`: Creates a tensor with random values uniformly sampled between 0 and 1
* `torch.randn`: Creates a tensor with random values sampled from a normal distribution with mean 0 and variance 1
* `torch.arange`: Creates a tensor containing the values $N,N+1,N+2,...,M$
* `torch.Tensor` (input list): Creates a tensor from the list elements you provide
* `torch.from_numpy`: Converts a numpy array into a PyTorch tensor

In [202]:
## TODO: Create a tensor from a list [[1, 2], [3, 4], [5, 6, 7]]
x = torch.tensor([[1, 2],[3, 4],[5, 6]])
print(x)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [207]:
## TODO: Create a tensor with random values between 0 and 1 with the shape [2, 3, 4]
x = torch.rand([2, 2, 4])
print(x)

tensor([[[0.2783, 0.4820, 0.8198, 0.9971],
         [0.6984, 0.5675, 0.8352, 0.2056]],

        [[0.5932, 0.1123, 0.1535, 0.2417],
         [0.7262, 0.7011, 0.2038, 0.6511]]])


You can obtain the shape of a tensor in the same way as in numpy (`x.shape`), or using the `.size` method:

In [208]:
shape = x.shape
print("Shape:", x.shape)

size = x.size()
print("Size:", size)

dim1, dim2, dim3 = x.size()
print("Size:", dim1, dim2, dim3)

Shape: torch.Size([2, 2, 4])
Size: torch.Size([2, 2, 4])
Size: 2 2 4


#### Operations

Most operations that exist in numpy, also exist in PyTorch. A full list of operations can be found in the [PyTorch documentation](https://pytorch.org/docs/stable/tensors.html#), but we will review the most important ones here.

The simplest operation is to add two tensors:

In [210]:
x1 = torch.rand(2, 3)
x2 = torch.rand(2, 3)

x1 = torch.tensor([1, 2, 3])
x2 = torch.tensor([1, 1, 1])

## TODO: Sum up the tensors x1 and x2, and store the result in y
y = x1 + x2

print("X1", x1)
print("X2", x2)
print("Y", y)

X1 tensor([1, 2, 3])
X2 tensor([1, 1, 1])
Y tensor([2, 3, 4])


Calling `x1 + x2` creates a new tensor containing the sum of the two inputs. However, we can also use in-place operations that are applied directly on the memory of a tensor. We therefore change the values of `x2` without the chance to re-accessing the values of `x2` before the operation. An example is shown below:

In [211]:
x1 = torch.tensor([1, 2, 3])
x2 = torch.tensor([2, 3, 4])
print("X1 (before)", x1)
print("X2 (before)", x2)

x2.add_(x1)
print("X1 (after)", x1)
print("X2 (after)", x2)

X1 (before) tensor([1, 2, 3])
X2 (before) tensor([2, 3, 4])
X1 (after) tensor([1, 2, 3])
X2 (after) tensor([3, 5, 7])


In-place operations are usually marked with a underscore postfix (e.g. "add_" instead of "add").

Another common operation aims at changing the shape of a tensor. A tensor of size (2,3) can be re-organized to any other shape with the same number of elements (e.g. a tensor of size (6), or (3,2), ...). In PyTorch, this operation is called `view`:

In [212]:
## TODO: Create a tensor with the input values [0, .., 5] (i.e. a range to 6)
x = torch.arange(0,6)
print("X", x)

X tensor([0, 1, 2, 3, 4, 5])


In [218]:
x = x.view(2, 3)
print("X", x)

X tensor([[0, 1, 2],
        [3, 4, 5]])


In [220]:
x = x.permute(0, 1) # Swapping dimension 0 and 1
print("X", x)

X tensor([[0, 3],
        [1, 4],
        [2, 5]])


Other commonly used operations include matrix multiplications, which are essential for neural networks. Quite often, we have an input vector $\mathbf{x}$, which is transformed using a learned weight matrix $\mathbf{W}$. There are multiple ways and functions to perform matrix multiplication, some of which we list below:

* `torch.matmul`: Performs the matrix product over two tensors, where the specific behavior depends on the dimensions. If both inputs are matrices (2-dimensional tensors), it performs the standard matrix product. For higher dimensional inputs, the function supports broadcasting (for details see the [documentation](https://pytorch.org/docs/stable/generated/torch.matmul.html?highlight=matmul#torch.matmul)). Can also be written as `a @ b`, similar to numpy. 
* `torch.mm`: Performs the matrix product over two matrices, but doesn't support broadcasting (see [documentation](https://pytorch.org/docs/stable/generated/torch.mm.html?highlight=torch%20mm#torch.mm))
* `torch.bmm`: Performs the matrix product with a support batch dimension. If the first tensor $T$ is of shape ($b\times n\times m$), and the second tensor $R$ ($b\times m\times p$), the output $O$ is of shape ($b\times n\times p$), and has been calculated by performing $b$ matrix multiplications of the submatrices of $T$ and $R$: $O_i = T_i @ R_i$
* `torch.einsum`: Performs matrix multiplications and more (i.e. sums of products) using the Einstein summation convention. Explanation of the Einstein sum can be found in assignment 1.

Usually, we use `torch.matmul` or `torch.bmm`. We can try a matrix multiplication with `torch.matmul` below.

In [221]:
x = torch.arange(6)
x = x.view(2, 3)
print("X", x)

X tensor([[0, 1, 2],
        [3, 4, 5]])


In [222]:
W = torch.arange(9).view(3, 3) # We can also stack multiple operations in a single line
print("W", W)

W tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [229]:
## TODO: Perform a matrix multiplication between x and W
h = x.matmul(W)
print("h", h)
# Verify the result by calculating it by hand too!

h tensor([[15, 18, 21],
        [42, 54, 66]])


In [228]:
A = torch.randn(5, 2, 2)  
B = torch.randn(5, 2, 4)     
#C1 = A.matmul(B)
#print(C1.shape)
C1 = torch.bmm(A,B)
print(C1.shape)

torch.Size([5, 2, 4])


#### Indexing

We often have the situation where we need to select a part of a tensor. Indexing works just like in numpy, so let's try it:

In [230]:
x = torch.arange(12).view(3, 4)
print("X", x)

X tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [231]:
## TODO: Print the second column of the tensor x
print(x[:,1]) 

tensor([1, 5, 9])


In [232]:
## TODO: Print the first row of the tensor x
print(x[0,:])

tensor([0, 1, 2, 3])


In [233]:
## TODO: Print the elements of the tensor x that are both in first two rows and the last column 
print(x[0:2,-1])

tensor([3, 7])


In [234]:
## TODO: Print the middle  row of tensor x
print(x[1:2,:])

tensor([[4, 5, 6, 7]])


### The Power of PyTorch: Dynamic Computation Graph and Automatic Gradients

PyTorch stands out as a go-to choice in the realm of Deep Learning due to its remarkable ability to automatically calculate the derivatives or gradients of the functions we define. In the context of our Deep Learning projects, we often work with neural networks, essentially sophisticated functions. These functions frequently involve weight matrices, which we refer to as the "parameters" or simply the "weights."

When our neural network yields a single scalar value, we commonly speak of taking its "derivative." However, you will notice that we often deal with scenarios where multiple output variables (or "values") are generated. In such cases, the term "gradients" is more appropriate, as it encompasses this broader concept.

Let's consider an input represented as $\mathbf{x}$. Our function is shaped by manipulating this input, typically involving matrix multiplications with weight matrices and adding bias vectors. As we perform these operations on our input, a "computational graph" is automatically constructed. This graph elucidates the path from our input to the final output. Notably, PyTorch follows a "define-by-run" approach, enabling us to focus on our manipulations while PyTorch meticulously tracks and manages the construction of this dynamic computation graph.

In summary, our primary task is to compute the desired "output." Subsequently, we can effortlessly call upon PyTorch to compute the gradients for us.

> **Why do we seek gradients?** Consider that we've formulated a neural network tasked with computing an output, denoted as $y$, for a given input vector $\mathbf{x}$. We also define an "error measure" that quantifies the discrepancy between our network's prediction of $y$ for input $\mathbf{x}$ and the actual value we desire. Armed with this error measure, we leverage the gradients to iteratively "update" the weights $\mathbf{W}$ responsible for the output. By doing so, we gradually steer the network towards generating output that aligns more closely with our target.

Our journey commences with the essential step of specifying which tensors necessitate gradients. By default, newly created tensors do not require gradients.

In [235]:
x = torch.ones((3,))
print(x.requires_grad)

False


We can change this for an existing tensor using the function `requires_grad_()` (underscore indicating that this is a in-place operation). Alternatively, when creating a tensor, you can pass the argument `requires_grad=True` to most initializers we have seen above.

In [236]:
x.requires_grad_(True)
print(x.requires_grad)

True


In order to get familiar with the concept of a computation graph, we will create one for the following function:

$$y = \frac{1}{|x|}\sum_i \left[(x_i + 2)^2 + 3\right]$$

You could imagine that $x$ are our parameters, and we want to optimize (either maximize or minimize) the output $y$. For this, we want to obtain the gradients $\partial y / \partial \mathbf{x}$. For our example, we'll use $\mathbf{x}=[0,1,2]$ as our input.

In [238]:
## TODO: Create a tensor with values [0.0, 1.0, 2.0] which is requires gradients
# Note that only float tensors can have gradients
x = torch.tensor([0., 1., 2.], dtype=torch.float32)
x.requires_grad_(True)
print("X", x)

X tensor([0., 1., 2.], requires_grad=True)


Now let's build the computation graph step by step. You can combine multiple operations in a single line, but we will separate them here to get a better understanding of how each operation is added to the computation graph.

In [239]:
## TODO: Implement the function above in four steps, each representing one single operation (add -> a, square -> b, add -> c, mean -> y)
a = x + 2
b = a**2
c = b + 3
y = torch.sum(c) / len(x)
print("Y", y)

Y tensor(12.6667, grad_fn=<DivBackward0>)


Using the statements above, we have created a computation graph that looks similar to the figure below:

<center style="width: 100%"><img src="pytorch_computation_graph.svg" width="200px"></center>

We calculate $a$ based on the inputs $x$ and the constant $2$, $b$ is $a$ squared, and so on. The visualization is an abstraction of the dependencies between inputs and outputs of the operations we have applied.
Each node of the computation graph has automatically defined a function for calculating the gradients with respect to its inputs, `grad_fn`. You can see this when we printed the output tensor $y$. This is why the computation graph is usually visualized in the reverse direction (arrows point from the result to the inputs). We can perform backpropagation on the computation graph by calling the function `backward()` on the last output, which effectively calculates the gradients for each tensor that has the property `requires_grad=True`:

In [240]:
y.backward()

`x.grad` will now contain the gradient $\partial y/ \partial \mathcal{x}$, and this gradient indicates how a change in $\mathbf{x}$ will affect output $y$ given the current input $\mathbf{x}=[0,1,2]$:

In [241]:
print(x.grad)

tensor([1.3333, 2.0000, 2.6667])


We can also verify these gradients by hand. We will calculate the gradients using the chain rule, in the same way as PyTorch did it:

$$\frac{\partial y}{\partial x_i} = \frac{\partial y}{\partial c_i}\frac{\partial c_i}{\partial b_i}\frac{\partial b_i}{\partial a_i}\frac{\partial a_i}{\partial x_i}$$

Note that we have simplified this equation to index notation, and by using the fact that all operation besides the mean do not combine the elements in the tensor. The partial derivatives are:

$$
\frac{\partial a_i}{\partial x_i} = 1,\hspace{1cm}
\frac{\partial b_i}{\partial a_i} = 2\cdot a_i\hspace{1cm}
\frac{\partial c_i}{\partial b_i} = 1\hspace{1cm}
\frac{\partial y}{\partial c_i} = \frac{1}{3}
$$

Hence, with the input being $\mathbf{x}=[0,1,2]$, our gradients are $\partial y/\partial \mathbf{x}=[4/3,2,8/3]$. The previous code cell should have printed the same result.

### Harnessing the Power of GPUs

One of the fundamental advantages of PyTorch is its compatibility with Graphics Processing Units (GPUs). A GPU is a specialized hardware unit designed for parallel processing, which makes it exceptionally well-suited for handling extensive matrix operations in neural networks. To understand the distinctions between GPUs and CPUs, we can refer to the insights shared by Kevin Krewell in a blog post from 2009 ([source](https://blogs.nvidia.com/blog/2009/12/16/whats-the-difference-between-a-cpu-and-a-gpu/)).

<center style="width: 100%"><img src="comparison_CPU_GPU.png" width="700px"></center>

CPUs and GPUs each have their unique strengths and weaknesses, which is why many computer systems incorporate both components, leveraging them for different computational tasks. If you're new to GPUs and wish to delve deeper into the topic, you can explore more information in this [NVIDIA blog post](https://blogs.nvidia.com/blog/2009/12/16/whats-the-difference-between-a-cpu-and-a-gpu/) or visit this [Intel page](https://www.intel.com/content/www/us/en/products/docs/processors/what-is-a-gpu.html).

The significance of GPUs in the context of neural networks lies in their ability to accelerate network training by a factor of up to 100, particularly beneficial for large-scale neural networks. PyTorch provides extensive support for GPUs, primarily focusing on NVIDIA GPUs, thanks to libraries such as [CUDA](https://developer.nvidia.com/cuda-zone) and [cuDNN](https://developer.nvidia.com/cudnn). To begin, let's determine whether you have access to a GPU:

In [242]:
gpu_avail = torch.cuda.is_available()
print("Is the GPU available? %s" % str(gpu_avail))
# for mac silicon users
mps_avail = torch.backends.mps.is_available()
print("Is the MPS available? %s" % str(gpu_avail))

Is the GPU available? True
Is the MPS available? True


In [243]:
import torch

print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("Device name:", torch.cuda.get_device_name(0))

print("MPS available:", torch.backends.mps.is_available())
print("MPS built:", torch.backends.mps.is_built())

print("Current device:", torch.device("cuda" if torch.cuda.is_available() else "cpu"))


CUDA available: True
Device name: NVIDIA GeForce RTX 4060 Laptop GPU
MPS available: False
MPS built: False
Current device: cuda


If you have a GPU on your computer but the command above returns False, make sure you have the correct CUDA-version installed. The `dl2020` environment comes with the CUDA-toolkit 10.1, which is selected for the Lisa supercomputer. Please change it if necessary (CUDA 10.2 is currently common). On Google Colab, make sure that you have selected a GPU in your runtime setup (in the menu, check under `Runtime -> Change runtime type`). 

By default, all tensors you create are stored on the CPU. We can push a tensor to the GPU by using the function `.to(...)`, or `.cuda()`. However, it is often a good practice to define a `device` object in your code which points to the GPU if you have one, and otherwise to the CPU. Then, you can write your code with respect to this device object, and it allows you to run the same code on both a CPU-only system, and one with a GPU. Let's try it below. We can specify the device as follows: 

In [244]:
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
# uncomment the line below if you have apple silicon and have installed the compatible torch version
# device = torch.device("mps")
print("Device", device)

Device cuda


Now let's create a tensor and push it to the device:

In [245]:
x = torch.zeros(2, 3)

## TODO: Push the tensor to "device"
x = torch.zeros(2, 3).to(device)
print("X", x)

X tensor([[0., 0., 0.],
        [0., 0., 0.]], device='cuda:0')


In case you have a GPU, you should now see the attribute `device='cuda:0'` (or `device='mps:0'`for mac users) being printed next to your tensor. The zero next to cuda indicates that this is the zero-th GPU device on your computer. PyTorch also supports multi-GPU systems, but this you will only need once you have very big networks to train (if interested, see the [PyTorch documentation](https://pytorch.org/docs/stable/distributed.html#distributed-basics)). We can also compare the runtime of a large matrix multiplication on the CPU with a operation on the GPU:

In [246]:
x = torch.randn(5000, 5000)

## CPU version
start_time = time.time()
_ = torch.matmul(x, x)
end_time = time.time()
print("CPU time: %6.5fs" % (end_time - start_time))

## GPU version
x = x.to(device)
# The first operation on a CUDA device can be slow as it has to establish a CPU-GPU communication first. 
# Hence, we run an arbitrary command first without timing it for a fair comparison.
if torch.cuda.is_available():
    _ = torch.matmul(x*0.0, x)
start_time = time.time()
_ = torch.matmul(x, x)
end_time = time.time()
print("GPU time: %6.5fs" % (end_time - start_time))

CPU time: 0.76722s
GPU time: 0.00091s


The acceleration of this operation can vary significantly depending on the size of the task and the CPU/GPU configuration of your system. In some cases, you may experience a speedup of over 500 times, although this might be less pronounced on Apple Silicon devices. Given that matrix multiplication (referred to as `matmul` operations) is a fundamental component in neural networks, the advantages of using a GPU for training become evident. It's worth noting that the time estimate can be somewhat unreliable at this point since we haven't conducted multiple runs. Expanding on this, it's important to mention that running on a GPU may also require more time for execution.

When generating random numbers, it's essential to be aware that the seed values for the CPU and GPU are not synchronized. To ensure code reproducibility, it is necessary to set the random number seed separately on the GPU. Keep in mind that due to variations in GPU architectures, running the same code on different GPUs may not yield identical random numbers. Nevertheless, it's crucial for our code to produce consistent results when executed on the same hardware. Therefore, we take the extra step of setting the seed on the GPU as well:

In [247]:
# GPU operations have a separate seed we also want to set
if torch.cuda.is_available(): 
    torch.cuda.manual_seed(42)
    torch.cuda.manual_seed_all(42)
    
# Additionally, some operations on a GPU are implemented stochastic for efficiency
# We want to ensure that all operations are deterministic on GPU (if used) for reproducibility
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

## Learning through Example: Text Classification

When working with PyTorch to construct a neural network, it's possible to define all the network's parameters, including weight matrices and bias vectors, using `Tensors` with `requires_grad=True`. PyTorch can then handle the gradient calculations and parameter adjustments. However, this approach can become unwieldy when dealing with a large number of parameters. To simplify the process, PyTorch offers a package called `torch.nn` specifically designed to facilitate the creation of neural networks.

In this tutorial, we will provide an overview of the essential libraries and components required for training a neural network in PyTorch. We'll use a straightforward example in the context of natural language processing (NLP) – text classification. Given a document, denoted as $d$, as our input, our goal is to predict the category or class to which the document belongs, represented as $y$. To achieve this, we intend to learn a function, denoted as $f_{\theta}(x)$, which is parameterized by $\theta$. This function takes input documents and provides us with a probability distribution across the available classes.

Throughout this tutorial, you will learn how to create a compact neural network capable of learning and implementing this function effectively.

### The data

PyTorch also provides a few functionalities to load the training and test data efficiently, summarized in the package `torch.utils.data`.

In [248]:
import torch.utils.data as data

The data package defines two classes which are the standard interface for handling data in PyTorch: `data.Dataset`, and `data.DataLoader`. The dataset class provides an uniform interface to access the training/test data, while the data loader makes sure to efficiently load and stack the data points from the dataset into batches during training.

#### The dataset class

The dataset class summarizes the basic functionality of a dataset in a natural way. To define a dataset in PyTorch, we simply specify two functions: `__getitem__`, and `__len__`. The get-item function has to return the $i$-th data point in the dataset, while the len function returns the size of the dataset. For the document dataset dataset, we can define the dataset class as follows:

In [249]:
class DocDataset(data.Dataset):
    def __init__(self):
        super().__init__()
        self.generate_document_data()

    def generate_document_data(self):
        from sklearn.datasets import fetch_20newsgroups
        from sklearn.feature_extraction.text import CountVectorizer
        categories = ['alt.atheism', 'soc.religion.christian', 'comp.graphics', 'sci.med']
        twenty_train = fetch_20newsgroups(subset='train', categories=categories, shuffle=True, random_state=42)
        count_vect = CountVectorizer()
        X = count_vect.fit_transform(twenty_train.data).toarray()

        self.data  = torch.tensor(X, dtype=torch.float32)        
        self.label = torch.tensor(twenty_train.target, dtype=torch.long)  
        self.features = self.data.shape[1]
        self.vocab = count_vect.vocabulary_

    def __len__(self):
        return self.data.shape[0]

    def __getitem__(self, idx):
        return self.data[idx], self.label[idx]


Let's try to create such a dataset and inspect it:

In [250]:
dataset = DocDataset()
print("Size of dataset:", len(dataset))
print("Data point 0:", dataset[0])
# also lets print the vocab
# print(dataset.vocab) (uncomment at your own risk :p)

Size of dataset: 2257
Data point 0: (tensor([0., 0., 0.,  ..., 0., 0., 0.]), tensor(1))


In [251]:
x0, y0 = dataset[0]
print("Label id:", y0.item())

nz = torch.nonzero(x0, as_tuple=True)[0]
print("Nonzero count:", nz.numel())
print("First 10 nonzero column indices:", nz[:10].tolist())

print("First 10 counts:", x0[nz[:10]].tolist())

inv_vocab = {j: w for w, j in dataset.vocab.items()}
print("First 10 tokens:", [inv_vocab[j] for j in nz[:10].tolist()])

sparsity = 1 - (nz.numel() / x0.numel())
print(f"Sparsity: {sparsity:.4%}")


Label id: 1
Nonzero count: 73
First 10 nonzero column indices: [177, 230, 587, 2326, 3062, 3166, 4017, 4378, 4808, 5195]
First 10 counts: [2.0, 1.0, 1.0, 2.0, 1.0, 1.0, 2.0, 1.0, 1.0, 1.0]
First 10 tokens: ['071', '0hb', '14', '477', '8000', '8565', 'ac', 'advance', 'also', 'any']
Sparsity: 99.7960%


In [252]:
x0, y0 = dataset[0]

print(x0.shape, x0.dtype)   
print(y0.item(), y0.dtype)  


torch.Size([35788]) torch.float32
1 torch.int64


In [253]:
l_list = dataset[0][0].tolist()   
l = [i for i in l_list  if i == 1]
len(l)

57

#### The data loader class

The class `torch.utils.data.DataLoader` represents a Python iterable over a dataset with support for automatic batching, multi-process data loading and many more features. The data loader communicates with the dataset using the function `__getitem__`, and stacks its outputs as tensors over the first dimension to form a batch.
In contrast to the dataset class, we usually don't have to define our own data loader class, but can just create an object of it with the dataset as input. Additionally, we can configure our data loader with the following input arguments (only a selection, see full list [here](https://pytorch.org/docs/stable/data.html#torch.utils.data.DataLoader)):

* `batch_size`: Number of samples to stack per batch
* `shuffle`: If True, the data is returned in a random order. This is important during training for introducing stochasticity. 
* `drop_last`: If True, the last batch is dropped in case it is smaller than the specified batch size. This occurs when the dataset size is not a multiple of the batch size. Only potentially helpful during training to keep a consistent batch size.

Let's create a simple data loader below:

In [254]:
data_loader = data.DataLoader(dataset, batch_size=3, shuffle=True)

In [255]:
#Dataset = [A, B, C, D, E, F]
#Epoch 1 batches:
#→ [A, B]
#→ [C, D]
#→ [E, F]

#Epoch 2:
#→ [A, B]
#→ [C, D]
#→ [E, F]


#Epoch 1
#→ [D, A]
#→ [E, F]
#→ [B, C]

#Epoch 2

#→ [C, E]
#→ [A, D]
#→ [B, F]


In [256]:
data_inputs, data_labels = next(iter(data_loader))

print("Data inputs", data_inputs.shape, "\n", data_inputs)
print("Data labels", data_labels.shape, "\n", data_labels)

Data inputs torch.Size([2, 35788]) 
 tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])
Data labels torch.Size([2]) 
 tensor([2, 3])


### The Model

The `torch.nn` package encompasses a range of valuable classes, including linear network layers, activation functions, loss functions, and more. You can explore a comprehensive list of these classes in the [official documentation](https://pytorch.org/docs/stable/nn.html). If you require a specific network layer for your project, it's advisable to consult the package documentation before attempting to implement it from scratch, as the package often provides pre-existing code for these layers. We've imported the package below for your reference:

In [ ]:
import torch.nn as nn

In addition to `torch.nn`, there is another important module called `torch.nn.functional`. This module comprises functions that are commonly employed within network layers. Notably, while `torch.nn` defines these functions as `nn.Modules` (we'll delve into this in more detail shortly), `torch.nn` itself relies extensively on the functionalities provided by `torch.nn.functional`. Therefore, the functional package proves to be highly valuable in various scenarios. As a result, we also include its import in this context:

In [ ]:
import torch.nn.functional as F

#### nn.Module

In PyTorch, a neural network is build up out of modules. Modules can contain other modules, and a neural network is considered to be a module itself as well. The basic template of a module is as follows:

In [ ]:
class MyModule(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, x):
        return x


The `forward` function serves as the core of a module, where the actual computation takes place. It gets executed when you call the module, typically in the form of `nn = MyModule(); nn(x)`. On the other hand, in the `init` function, we typically set up the module's parameters using `nn.Parameter` or define other modules that will be utilized within the `forward` function. It's important to note that the backward calculation, which handles gradients and backpropagation, is automatically managed by PyTorch, but it can also be customized if needed.

#### Simple Classifier

Now, armed with the pre-defined modules from the `torch.nn` package, we can proceed to design our own compact neural network. In this example, we'll create a minimal network consisting of an input layer, a single hidden layer with a tanh activation function, and an output layer. In other words, our network architecture should resemble the following diagram:

<center width="100%"><img src="nn.png" width="300px"></center>

In this visualization, the blue nodes represent the input neurons, which correspond to the data point's features. The yellow nodes represent the hidden neurons, featuring a tanh activation function, and the red node represents the output neuron. In PyTorch, you can define this neural network as follows:

In [ ]:
import torch
import torch.nn as nn

class SimpleClassifier(nn.Module):
    def __init__(self, num_inputs, num_hidden, num_outputs):
        super().__init__()
        self.linear1 = nn.Linear(num_inputs, num_hidden)
        self.act_fn = nn.ReLU()
        self.linear2 = nn.Linear(num_hidden, num_outputs)

    def forward(self, x):
        x = self.linear1(x)    #[B,num_hidden]
        x = self.act_fn(x)     #[B,num_hidden]
        x = self.linear2(x)    #[B,Num_clases]
        return x

In the examples presented in this notebook, we'll employ a compact neural network featuring two input neurons and four hidden neurons. Since we're dealing with straightforward classification tasks, the output dimension of the network corresponds to the number of classes we are classifying into. It's worth noting that we do not apply a softmax activation function to the output at this stage. The rationale behind this choice is that for various computations, especially those related to loss functions, it is often more efficient and accurate to work with the original network outputs rather than applying softmax. We'll delve into the detailed explanation for this decision later in the tutorial.

In [ ]:
model = SimpleClassifier(num_inputs=dataset.features, num_hidden=256, num_outputs=4)
print(model)

Printing the model lists all submodules it contains. The parameters of a module can be obtained by using its `parameters()` functions, or `named_parameters()` to get a name to each parameter object. For our small neural network, we have the following parameters:

In [ ]:
for name, param in model.named_parameters():
    print("Parameter %s, shape %s" % (name, str(param.shape)))

Each linear layer has a weight matrix of the shape `[output, input]`, and a bias of the shape `[output]`. The tanh activation function does not have any parameters. Note that parameters are only registered for `nn.Module` objects that are direct object attributes, i.e. `self.a = ...`. If you define a list of modules, the parameters of those are not registered for the outer module and can cause some issues when you try to optimize your module. There are alternatives, like `nn.ModuleList`, `nn.ModuleDict` and `nn.Sequential`, that allow you to have different data structures of modules. We will use them in a few later tutorials and explain them there. 

### Model Optimization Workflow

Once the model and dataset are defined, the next step is to set up the optimization process for the model. During the training phase, the following key steps are executed:

1. **Data Batch Retrieval:** Fetch a batch of data from the data loader.
2. **Model Predictions:** Obtain predictions from the model for the batch.
3. **Loss Calculation:** Compute the loss by assessing the disparity between predictions and actual labels.
4. **Backpropagation:** Calculate the gradients for each model parameter with respect to the loss.
5. **Parameter Updates:** Update the model's parameters by moving them in the direction indicated by the gradients.

Up to this point, we have discussed how to perform steps 1, 2, and 4 using PyTorch. Now, we will delve into the details of steps 3 and 5.

#### Loss Computation Modules

To calculate the loss for a batch, we can leverage the power of tensor operations, as these are seamlessly integrated into the computation graph. For instance, in the context of multi-class classification, the Cross Entropy (CE) loss is a commonly used metric, defined as:

$$\mathcal{L}_{CE} = \sum_i y_i \log x_i $$

Here, $y$ represents the labels, and $x$ signifies our model's predictions. However, PyTorch offers a selection of pre-defined loss functions for our convenience (refer to the full list [here](https://pytorch.org/docs/stable/nn.html#loss-functions)). In the case of CE, PyTorch provides `nn.CrossEntropyLoss`, which is recommended for its numerical stability. This is due to the softmax operation applied within the loss function. Therefore, it is advisable to employ loss functions that operate on "logits" whenever possible (without applying a softmax to the model's output in this scenario). In the context of the model defined earlier, we opt to utilize the `nn.CrossEntropyLoss` module. Please read the documentations of `nn.CrossEntropyLoss` [here](https://pytorch.org/docs/stable/generated/torch.nn.CrossEntropyLoss.html).

In [ ]:
loss_module = nn.CrossEntropyLoss()

#### Stochastic Gradient Descent (SGD)

In the context of parameter updates, PyTorch offers the `torch.optim` package, which incorporates a variety of widely-used optimization algorithms. Detailed discussions about specific optimizers and their distinctions will follow later in the course. For now, we will employ one of the simplest optimization techniques: `torch.optim.SGD`. Stochastic Gradient Descent operates by scaling the gradients with a small constant known as the learning rate and then subtracting this scaled value from the model's parameters, effectively reducing the loss. As a result, this process gradually steers the model towards minimizing the loss function. A suitable default learning rate for a modest-sized network, such as the one we have, is typically set at 0.001.

In [ ]:
ptimizer = torch.optim.SGD(model.parameters(), lr=0.001)

The optimizer provides two essential functions: `optimizer.step()` and `optimizer.zero_grad()`. The `step` function handles parameter updates based on the previously computed gradients, as described earlier. On the other hand, the function `optimizer.zero_grad()` plays a crucial role, especially prior to backpropagation. While it might seem less significant at first glance, it is a vital preparatory step. If we were to invoke the `backward` function on the loss when parameter gradients still retain non-zero values from the previous batch, the new gradients would be added to the existing ones rather than overwriting them.

This behavior occurs because a parameter can appear multiple times in a computation graph, and in such cases, we need to sum the gradients instead of replacing them. Therefore, it's imperative to remember to call `optimizer.zero_grad()` to reset the gradients to zero before calculating the gradients for a new batch.

### Training

Finally, we are ready to train our model. As a first step, we create a slightly larger dataset and specify a data loader with a larger batch size. 

In [ ]:
train_dataset = DocDataset()
train_dataset, test_dataset = data.random_split(train_dataset, [0.8, 0.2]) 
train_data_loader = data.DataLoader(train_dataset, batch_size=128, shuffle=True)

Now, let's construct a concise training function. Recall the five key steps in our training process: load a batch, acquire predictions, calculate the loss, perform backpropagation, and update the model's parameters. In addition to these steps, we must also ensure that all data and model parameters are transferred to the device of our choice, typically the GPU if available.

It's important to note that for our small neural network, the data transfer to the GPU consumes more time than the potential performance gain from GPU acceleration. In cases involving larger networks, the time spent on data communication becomes significantly smaller relative to the overall runtime, making a GPU an essential asset. However, for the sake of practice, we will push the data to the GPU in this example.

In [ ]:
# Push model to device. Has to be only done once
device = "cuda"
model.to(device)

In addition, we set our model to training mode. This is done by calling `model.train()`. There exist certain modules that need to perform a different forward step during training than during testing (e.g. BatchNorm and Dropout), and we can switch between them using `model.train()` and `model.eval()`.

In [ ]:
def train_model(model, optimizer, data_loader, loss_module, num_epochs=100):
    model.train() 
 
    for epoch in tqdm(range(num_epochs), desc="Epoch"):
        for i, (data_inputs, data_labels) in enumerate(data_loader):
            data_inputs = data_inputs.to(device)
            data_labels = data_labels.to(device)
            preds = model(data_inputs)            
            loss = loss_module(preds, data_labels)
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            if i % 100 == 0:
                print(f"Epoch: {epoch}, Iteration: {i}, Loss: {loss.item():.4f}")
    return model, optimizer


In [ ]:
train_model(model, optimizer, train_data_loader, loss_module)

#### Saving a model

After finish training a model, we save the model to disk so that we can load the same weights at a later time. For this, we extract the so-called `state_dict` from the model which contains all learnable parameters. For our simple model, the state dict contains the following entries:

In [ ]:
state_dict = model.state_dict()
print(state_dict)

To save the state dictionary, we can use `torch.save`:

In [ ]:
# torch.save(object, filename). For the filename, any extension can be used
torch.save(state_dict, "our_model.tar")

To load a model from a state dict, we use the function `torch.load` to load the state dict from the disk, and the module function `load_state_dict` to overwrite our parameters with the new values:

In [ ]:
# Load state dict from the disk (make sure it is the same name as above)
state_dict = torch.load("our_model.tar")

# Create a new model and load the state
new_model = SimpleClassifier(num_inputs=dataset.features, num_hidden=256, num_outputs=4)
new_model.load_state_dict(state_dict)

# Verify that the parameters are the same
print("Original model\n", model.state_dict())
print("\nLoaded model\n", new_model.state_dict())

A detailed tutorial on saving and loading models in PyTorch can be found [here](https://pytorch.org/tutorials/beginner/saving_loading_models.html).

### Evaluation

Once we have trained a model, it is time to evaluate it on a held-out test set. As our dataset consist of randomly generated data points, we need to first create a test set with a corresponding data loader.

In [ ]:
test_data_loader = data.DataLoader(test_dataset, batch_size=128, shuffle=True)

We will employ accuracy as our metric, computed using the following formula:

$$\text{accuracy} = \frac{\text{number of correct predictions}}{\text{total number of predictions}}$$

When assessing the model, there's no need to maintain the computational graph since we won't be performing gradient calculations. This optimization reduces memory usage and enhances model speed. In PyTorch, you can disable the computation graph with the `torch.no_grad()` context manager. Additionally, don't forget to switch the model to evaluation mode.

In [ ]:
def eval_model(model, data_loader):
    model.eval() 
    device = next(model.parameters()).device  
    true_preds, num_preds = 0, 0

    with torch.no_grad():  
        for data_inputs, data_labels in data_loader:
            data_inputs = data_inputs.to(device)
            if not torch.is_floating_point(data_inputs):
                data_inputs = data_inputs.float()
            data_labels = data_labels.to(device).long()

            logits = model(data_inputs)

            if logits.ndim == 1 or (logits.ndim == 2 and logits.shape[1] == 1):
                pred_labels = (torch.sigmoid(logits.view(-1)) >= 0.5).long()
            else:
                pred_labels = logits.argmax(dim=1)

            true_preds += (pred_labels == data_labels).sum().item()
            num_preds  += data_labels.size(0)

    acc = true_preds / num_preds if num_preds else 0.0
    print(f"Accuracy of the model: {100.0 * acc:4.2f}%")
    return acc


In [ ]:
eval_model(model, test_data_loader)

If we trained our model correctly, we should see a okay-ish accuracy. However, we can imporve it through some text preprocessing and more complex network.